# Generated by Django 2.0.7 on 2019-08-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bvisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.TextField()),
                ('enterprise_id', models.TextField()),
                ('project', models.TextField()),
                ('whatsapp_number', models.TextField()),
                ('travel_start_date', models.TextField()),
                ('travel_end_date', models.TextField()),
                ('capability', models.TextField()),
            ],
        ),
    ]
