# Generated by Django 2.0.7 on 2019-08-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bvisa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bvisa',
            name='capability',
            field=models.CharField(choices=[('1', 'option1'), ('2', 'option2')], max_length=1),
        ),
        migrations.AlterField(
            model_name='bvisa',
            name='employee_name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='bvisa',
            name='enterprise_id',
            field=models.EmailField(max_length=70),
        ),
        migrations.AlterField(
            model_name='bvisa',
            name='project',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bvisa',
            name='travel_start_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bvisa',
            name='whatsapp_number',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
