# Generated by Django 2.0.7 on 2019-08-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bvisa', '0002_auto_20190817_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bvisa',
            name='travel_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bvisa',
            name='travel_start_date',
            field=models.DateField(),
        ),
    ]
