# Generated by Django 2.0.7 on 2019-08-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcp',
            name='capability',
            field=models.CharField(choices=[('Capability1', 'Capability1'), ('Capability2', 'Capability2')], max_length=20),
        ),
        migrations.AlterField(
            model_name='gcp',
            name='employee_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='gcp',
            name='enterprise_id',
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name='gcp',
            name='project',
            field=models.CharField(choices=[('Cigna', 'Cigna'), ('Anthem', 'Anthem')], max_length=20),
        ),
    ]
